version: '3.4'

services:
  catalogodb:
    image: postgres

  basketdb:
    image: postgres
  
  distributedcache:
    image: redis
  
  orderdb:
    image: mcr.microsoft.com/mssql/server

  catalogo.api:
    image: ${DOCKER_REGISTRY-}catalogoapi
    build:
      context: .
      dockerfile: Serviços/Catalogo/Catalogo.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Serviços/Carrinho/Carrinho.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Serviços/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalogo:
  postgres_basket:  

