version: '3.4'

services:
  catalogodb:
    image: postgres

  basketdb:
    image: postgres
  
  distributedcache:
    image: redis

  catalogo.api:
    image: ${DOCKER_REGISTRY-}catalogoapi
    build:
      context: .
      dockerfile: Servi√ßos/Catalogo/Catalogo.API/Dockerfile

volumes:
  postgres_catalogo:
  postgres_basket:  